### ISSUE TITLE
Hey uh, what's up with this?

### ISSUE THREAD

**Issue by vincentwoo** [joranbeasley/CoderPad#1]

**Comment by joranbeasley** [comment]
thanks for asking @vincentwoo. its a tool to help conduct offsite interviews for programmers check out the new demo on the front page :) go ahead and install it and run it with the commands given (the first time you run it it *should* have you help set it up ...

**Comment by joranbeasley** [comment]
ahh i see ... basically its a cruddier version of your site ... hmmm maybe i should change the name

**Comment by vincentwoo** [comment]
Haha, its cool. Happy hacking!
